### ISSUE TITLE
Spring Creators Update (1803 / RS4) master issue + status tracking

### ISSUE THREAD

**Issue by Disassembler0** [Disassembler0/Win10-Initial-Setup-Script#72]
This is a master issue for all 1803 / RS4 shenanigans. I'll also track my work related to getting the script compatible with 1803 here. So far the commits will go into highly experimental [1803 branch](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/1803-experimental) until they're tested and readyish to be merged into master. **For a newly found problem, please create a separate issue, I'll handle the tracking afterwards.**

- [x] `DisableWebSearch` - RS4 ignores *DisableWebSearch* GPO. Search can be now disabled only via Cortana consent removal in HKCU - fixed in 7b3398fdd718128c1dbd3a5a7091cfa823ccd46a. The GPO part was retained just in case.
- [x] `DisableAppSuggestions` - RS4 adds ~~advertisements~~ *suggestions* also to the task view which now contains also history of previously run program and visited sites. One more registry with absolutely meaningless name (`SubscribedContent-353698Enabled`) takes care of that - implemented in fea6de81046fff076a986d8be8808aa3115164b9.
- [x] `DisableBackgroundApps` - RS4 fixes the problem with disabled Cortana background app breaking search indexing described in #40 and #42, while simultaneously introducing completely different problem. The master *Disable background apps* switch doesn't disable anything anymore. It just instructs Windows to delete the keys from `BackgroundAccessApplications` registry key during reboot and then re-enables the control, allowing the previously deleted apps to register again. Fortunately with the workaround introduced in 50362f3 no additional fixes are needed.
- [x] `DisableLocationTracking` - Disabling location tracking now needs to use capability manager instead of lfscv service configuration - fixed in 4b8a519ee015ba1c5631f2e6715792b3ff5d3ecc.
- [x] `SetP2PUpdateLocal` - P2P restricted to LAN seems to be the default for quite some time - coommented out in 749150e9e2068981b2649509e62a14799bbcf1cd.
- [x] `DisableAutoLogger` - The AutoLogger directory seems to be unused for quite some time (mentioned in #20), plus it was never confirmed what data does it collect and send (should be just system startup trace) - removed in eb82e5b85566502fc1bfc8ccc658766029a33a75.
- [x] `DisableUpdateDriver` - Seems like this actually never worked properly - fixed in 03e501b48159c5e7a8712ae0746b656579c98334. Additional note: This still doesn't work properly if you attempt to use a driver intended for another hardware model. Even with all the GPOs, Windows will offer their own in updates.
- [x] `DisableHomeGroups` - Home groups are dead? Really? Finally! - commended out in d4fe0001a9cf8606373ef1143c4a437a05b58522.
- [x] `DisableSharedExperiences` - Use GPO instead. There is also a new `EnableMmx` policy in RS4, so use that as well - implemented in 98e106b78ad5de2521945da38bebd4af1558071f.
- [x] `DisableLockScreenRS1` - The original `DisableLockScreen` seems to work again on RS4. Task manager workaround retained for compatibility.
- [x] `InstallLinuxSubsystem` - Check if the developer flags are still needed and remove if they aren't - updated in 5fa6f4409c3766f4a1680705415e55b4cdc35f3c.
- [x] `UnpinStartMenuTiles` doesn't work anymore, as reported in #71. Can't say I'm surprised as the original tweak was a shot in the dark - fixed in 488baa111f074429b414f302b49bc748169ed021.
- [x] New tweak - Disable activity history / timeline - implemented in 12b6cef3d15958ae97f13015d07faefe5e8b1903.
- [x] New tweak - Enable memory integrity (in core isolation in Defender) - implemented in 2c79e6fb1f8870f19c6c59ec8c47f8f3d7a50fad.
- [x] New tweak - Disable LLMNR - implemented in bf97bb5f7b0fa1be487eb165cda00e60ee0639d0.
- [x] New tweak - Hide Personal folders from start menu (left side) - It's again some binary blob under `$windows.data.unifiedtile.startglobalproperties` key. (╯°□°）╯︵ ┻━┻ I'm not going to implement it. I can already see the opened issue requesting different configurations.
- [x] Make use of GPO as much as possible. Rewrite existing tweaks if there is an appropriate GPO allowing to achieve the same result.
- [x] **Test everything**
